init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'
    
install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
build_script:
  - if not exist "C:\rtm" mkdir C:\rtm
  - set TMP=C:/rtm
  - set TEMP=C:/rtm
  - set TMPDIR=C:/rtm  
  - ls
  - echo "Downloading and installing travis_helpers"
  - ps: Invoke-WebRequest http://bit.ly/travis_helpers -OutFile "..\travis_helpers.sh"
  - echo '@bash.exe ../travis_helpers.sh %*' | Out-File -Encoding ASCII .\travis_helpers.sh.cmd
  - bash -c "echo '^travis_helpers\.sh\.cmd$' >> .Rbuildignore"
  - travis_helpers.sh install_missing_remote_deps stnava/ITKR
  - travis_helpers.sh gh_binary_install ${ants_user}/ITKR ;  
  # - ps: Invoke-WebRequest https://github.com/muschellij2/ITKR/releases/download/v0.4.17.1.0/ITKR_0.4.17.1_R3.5.zip -OutFile ".\ITKR.zip"  
  # - Rscript -e "install.packages('ITKR.zip', repos = NULL)"  
  # - rm ITKR.zip
  # - Rscript -e "x= read.dcf('DESCRIPTION', all = TRUE); x$Remotes = gsub('stnava/ITKR', '', x$Remotes); write.dcf(x, file = 'DESCRIPTION')"    
  - travis-tool.sh install_deps

test_script: 
  - travis-tool.sh run_tests
  - ls
  # - cp -r C:\run\* %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - ls

on_failure:
  - cat *.Rcheck/00install.out
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs
  - path: '*.Rcheck\**\*.out'
    name: Logs
  - path: '*.Rcheck\**\*.fail'
    name: Logs
  - path: '*.Rcheck\**\*.Rout'
    name: Logs
  - path: \*_*.zip
    name: Bits

environment:
  global:
    WARNINGS_ARE_ERORRS: 1.0
    USE_RTOOLS: yes
    R_CHECK_INSTALL_ARGS: --install-args=--build --no-multiarch
  matrix:
    - R_VERSION: release
      R_VER: 3.5    

deploy:
  provider: GitHub
  description: Windows Binary
  auth_token:
    secure: tc2Va9OWLH9H/uKPUKCUmv+q+wQpzRVJd6t8ckXjqzGnOo9eWyiQCmuuUjcuM3b8
  draft: false
  prerelease: falase
  on:
    appveyor_repo_tag: true

